const repo=require('../../../services/data/repository');
const {DISCLAIMER}=require('../../../services/shared/compliance');
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const U=(...c)=>String.fromCodePoint(...c);
const L={
brand:U(0x8d44,0x8baf,0x9898,0x6750,0x7ebf,0x7d22,0x5de5,0x5177),sub:U(0x53d1,0x73b0,0x9898,0x6750,0xff0c,0x628a,0x63e1,0x673a,0x4f1a),search:U(0x641c,0x7d22,0x8d44,0x8baf,0x3001,0x9898,0x6750,0x3001,0x516c,0x53f8,0x3001,0x4e8b,0x4ef6,0x7b49),home:U(0x9996,0x9875),news:U(0x8d44,0x8baf),theme:U(0x9898,0x6750),sample:U(0x6837,0x4f8b),
today:U(0x4eca,0x65e5,0x8d44,0x8baf),all:U(0x5168,0x90e8),macro:U(0x5b8f,0x89c2),industry:U(0x4ea7,0x4e1a),company:U(0x516c,0x53f8),policy:U(0x653f,0x7b56),
hot:U(0x70ed,0x95e8,0x9898,0x6750,0x699c),rank:U(0x6392,0x540d),themeName:U(0x9898,0x6750,0x540d,0x79f0),heat:U(0x70ed,0x5ea6),change:U(0x6da8,0x8dcc,0x5e45),tags:U(0x9898,0x6750,0x5206,0x7c7b,0x6807,0x7b7e),obs:U(0x4eca,0x65e5,0x89c2,0x5bdf),opp:U(0x9898,0x6750,0x673a,0x4f1a),cards:U(0x9898,0x6750,0x5361,0x7247),chainMap:U(0x4ea7,0x4e1a,0x94fe,0x56fe,0x8c31),up:U(0x4e0a,0x6e38),mid:U(0x4e2d,0x6e38),down:U(0x4e0b,0x6e38,0x5e94,0x7528),relatedCo:U(0x5173,0x8054,0x516c,0x53f8),trend:U(0x70ed,0x5ea6,0x8d8b,0x52bf),
missing:U(0x9898,0x6750,0x4e0d,0x5b58,0x5728),event:U(0x4e8b,0x4ef6,0x6458,0x8981),logic:U(0x9898,0x6750,0x903b,0x8f91),nodes:U(0x4ea7,0x4e1a,0x94fe,0x8282,0x70b9),evidence:U(0x8bc1,0x636e),risk:U(0x98ce,0x9669,0x63d0,0x793a),watch:U(0x89c2,0x5bdf,0x70b9),relatedTheme:U(0x76f8,0x5173,0x9898,0x6750),notFound:U(0x9875,0x9762,0x4e0d,0x5b58,0x5728),
about:U(0x5173,0x4e8e,0x6211,0x4eec),disclaimer:U(0x514d,0x8d23,0x58f0,0x660e),privacy:U(0x9690,0x79c1,0x653f,0x7b56),contact:U(0x8054,0x7cfb,0x6211,0x4eec),copy:U(0x7248,0x6743,0x6240,0x6709),hotTitle:U(0x70ed,0x5ea6),delta:U(0x6da8,0x8dcc)
};
function nav(a){return `<header class=top><div class=brand><div class=cube>F</div><div><strong>${L.brand}</strong><span>${L.sub}</span></div></div><div class=search>${L.search}</div><nav><a class=${a==='home'?'active':''} href=/>${L.home}</a><a class=${a==='news'?'active':''} href=/news>${L.news}</a><a class=${a==='themes'?'active':''} href=/themes>${L.theme}</a></nav></header>`}
function foot(){return `<footer><a>${L.about}</a><span>|</span><a>${L.disclaimer}</a><span>|</span><a>${L.privacy}</a><span>|</span><a>${L.contact}</a><p>${DISCLAIMER}</p><small>? 2026 ${L.brand} ${L.copy}</small></footer>`}
function layout(a,b){return `<!doctype html><html lang=zh-CN><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>FinaHunt ${L.brand}</title><link rel=stylesheet href=/styles.css></head><body>${nav(a)}${b}${foot()}<script src=/app.js></script></body></html>`}
function rank(items){return `<div class=card><h2>${L.hot}</h2><table><tr><th>${L.rank}</th><th>${L.themeName}</th><th>${L.heat}</th><th>${L.change}</th></tr>${items.map((r,i)=>`<tr><td><b class="rank r${i+1}">${i+1}</b></td><td><a href=/themes/${r.theme.id}>${e(r.theme.name)}</a></td><td>${r.heatScore}</td><td class=red>${r.heatChange}</td></tr>`).join('')}</table></div>`}
function tags(items){return `<div class=card><h2>${L.tags}</h2><div class=tags>${items.map(t=>`<a href=/themes?tag=${encodeURIComponent(t.name)}>${e(t.name)}</a>`).join('')}</div></div>`}
function newsList(items){return `<div class="card wide"><h2>${L.today}</h2><div class=filters><button>${L.all}</button><button>${L.macro}</button><button>${L.industry}</button><button>${L.company}</button><button>${L.policy}</button></div><div class=timeline>${items.map(n=>`<article class=news-item><time>${e((n.publishTime||'').slice(11,16))}</time><div><span class=cat>${e(n.category)}</span><h3>${e(n.title)}</h3><p>${e(n.summary)}</p><div class=chips>${(n.tags||[]).map(t=>`<i>${e(t)}</i>`).join('')}</div></div></article>`).join('')}</div></div>`}
function obs(items){return `<div class=card><h2>${L.obs}</h2>${items.map((o,i)=>`<p class=obs><b>${i+1}</b> ${e(o.text)}</p>`).join('')}</div>`}
function home(){const h=repo.home().data;return layout('home',`<main class=grid>${newsList(h.today_news)}<aside>${rank(h.hot_themes)}${tags(h.theme_tags)}${obs(h.today_observations)}</aside><section class="wide card"><h2>${L.opp}</h2><div class=metrics>${h.opportunity_widgets.map(w=>`<a class=metric href=/themes/${w.id}><b>${e(w.name)}</b><strong>${e(w.heatScore)}</strong><span>${e(w.summary)}</span></a>`).join('')}</div></section></main>`)}
function news(){const h=repo.home().data,n=repo.news({pageSize:10}).data;return layout('news',`<main class=grid>${newsList(n.items)}<aside>${rank(h.hot_themes)}${tags(h.theme_tags)}${obs(h.today_observations)}</aside></main>`)}
function themes(){const d=repo.themes().data,h=repo.home().data;return layout('themes',`<main class=grid><section class=wide>${rank(h.hot_themes)}<div class=card><h2>${L.cards}</h2><div class=theme-cards>${d.items.slice(0,8).map(t=>`<a class=theme-card href=/themes/${t.id}><b>${e(t.name)}</b><span class=red>${e(t.heatChange)}</span><p>${e(t.summary)}</p><div class=chips>${t.tags.slice(0,3).map(x=>`<i>${e(x)}</i>`).join('')}</div></a>`).join('')}</div></div><div class=card><h2>${L.chainMap}</h2><div class=chain><span>${L.up}</span><span>${L.mid}</span><span>${L.down}</span><span>${L.relatedCo}</span></div></div></section><aside>${tags(h.theme_tags)}<div class=card><h2>${L.trend}</h2>${d.items.slice(0,4).map(t=>`<div class=trend><b>${e(t.name)}</b><span>${t.trend.map(x=>'-???????'[Math.max(1,Math.min(7,Math.floor((x-50)/8)+1))]).join('')}</span></div>`).join('')}</div></aside></main>`)}
function box(t,it){return `<div class=card><h2>${t}</h2>${it.map(x=>`<p class=obs>${e(x)}</p>`).join('')}</div>`}
function detail(id){const r=repo.themeById(id);if(!r.ok)return layout('themes',`<main class=card><h1>${L.missing}</h1></main>`);const d=r.data,t=d.theme;return layout('themes',`<main class=detail><section class="hero card"><div class=illustration>?</div><div><h1>${e(t.name)} <small>${e(t.level)}</small></h1><p>${L.hotTitle} <b class=red>${e(t.heatScore)}</b> ${L.delta} <b class=red>${e(t.heatChange)}</b></p><p>${e(t.summary)}</p><div class=chips>${t.tags.map(x=>`<i>${e(x)}</i>`).join('')}</div></div></section><section class=card><h2>${L.event}</h2><p>${e(d.event_summary)}</p></section><section class=card><h2>${L.logic}</h2><p>${e(d.theme_logic)}</p></section><section class=card><h2>${L.nodes}</h2><div class=chain>${d.industry_chain_nodes.map(n=>`<span>${e(n.name)}</span>`).join('')}</div></section><section class=card><h2>${L.relatedCo}</h2><table>${d.related_companies.map(m=>`<tr><td>${e(m.companyName)}</td><td>${e(m.chainNode)}</td><td>${e(m.reason)}</td><td>${e(m.evidenceStrength)}</td></tr>`).join('')}</table></section><aside>${box(L.evidence,d.evidences.map(ev=>`${ev.sourceName}?${ev.title}`))}${box(L.risk,d.risks.map(r=>r.text))}${box(L.watch,d.observations.map(o=>o.text))}</aside><section class="card wide"><h2>${L.relatedTheme}</h2><div class=theme-cards>${d.related_themes.map(t=>`<a class=theme-card href=/themes/${t.id}><b>${e(t.name)}</b><p>${e(t.summary)}</p></a>`).join('')}</div></section></main>`)}
function admin(){const c=repo.counts();return layout('admin',`<main class="admin card"><h1>${L.sample}</h1><div class=metrics>${Object.entries(c).slice(0,12).map(([k,v])=>`<div class=metric><b>${e(k)}</b><strong>${v}</strong></div>`).join('')}</div></main>`)}
function renderPage(p){if(p==='/')return home();if(p==='/news')return news();if(p==='/themes')return themes();if(p.startsWith('/themes/'))return detail(p.split('/').pop());if(p.startsWith('/admin'))return admin();return layout('home',`<main class=card><h1>${L.notFound}</h1></main>`)}
module.exports={renderPage};
